### ISSUE TITLE
Problem when deploy wordpress app

### ISSUE THREAD

**Issue by gwmoura** [tsuru/platforms#17]
I have a wordpress app running normally, but when I tryed update it, I receive this error:

```bash
remote: Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
remote:  * Stopping Apache httpd web server apache2
remote:  * 
remote: update-rc.d: /etc/init.d/apache2 exists during rc.d purge (use -f to force)
remote: /usr/bin/env: php: No such file or directory
remote: Traceback (most recent call last):
remote:   File "/var/lib/tsuru/php/deploy.py", line 209, in <module>
remote:     manager.install()
remote:   File "/var/lib/tsuru/php/deploy.py", line 92, in install
remote:     self.install_composer()
remote:   File "/var/lib/tsuru/php/deploy.py", line 109, in install_composer
remote:     raise InstallationException('Unable to install composer dependencies')
remote: __main__.InstallationException: Unable to install composer dependencies
remote: Installing system packages...
remote: Install composer dependencies
remote: Composer is not found locally, downloading it
remote: 2016/04/24 15:37:24 exit status 1
remote: Exit status 1
To git@gcodetecapp.com:iblvwordpress.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@gcodetecapp.com:iblvwordpress.git'
```

The error occur in this line - https://github.com/tsuru/platforms/blob/master/php/deploy.py#L108

```python
if os.system('cd %s && %s install' % (self.application.get('directory'), composer_phar)) != 0:
                raise InstallationException('Unable to install composer dependencies')
```

Accessing the container and following this steps to simulate the error, I receive this error:

```shell
$ tsuru app-shell
ubuntu@67bd6a2c8453:/$ cd /home/application/current/
ubuntu@67bd6a2c8453:/home/application/current$ python -c 'import os; os.system("cd /home/application/current && ./composer.phar install")'
Cannot create cache directory /home/ubuntu/.composer/cache/repo/http---wpackagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/ubuntu/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/ubuntu/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update

                                                                                                                         
  [ErrorException]                                                                                                       
  file_put_contents(/home/application/current/vendor/composer/installed.json): failed to open stream: Permission denied  
                                                                                                                         

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

Running with sudo the script is executed normally:

```bash
$ python -c 'import os; os.system("cd /home/application/current && sudo ./composer.phar install")'
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

I think if we change `os.system('cd %s && %s install' % (self.application.get('directory')` to `os.system('cd %s && sudo %s install' % (self.application.get('directory'), composer_phar))`, composer_phar))` this problem is resolved.

**Comment by jroqueweb** [comment]
@gwmoura, you had progress with this?

**Comment by morpheu** [comment]
@gwmoura could you check if this still happen?  I've updated php platform and tested composer with success.

**Comment by gwmoura** [comment]
@morpheu @jroqueweb I'm sorry, I gonna test and return with a feedback
